# Generated by Django 6.0.6 on 2026-09-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_persona_rut_alter_persona_telefono'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='persona',
            managers=[
            ],
        ),
    ]
