# Generated by Django 6.0.6 on 2026-09-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
