# Generated by Django 6.0.6 on 2026-09-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_mascota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad en años', null=True),
        ),
    ]
