# Generated by Django 6.0.6 on 2026-09-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_mascota_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
