# Generated by Django 6.0.6 on 2026-09-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_mascota_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_unidad',
            field=models.CharField(blank=True, choices=[('años', 'Años'), ('meses', 'Meses')], default='años', max_length=10),
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_valor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
