# Generated by Django 6.0.6 on 2026-09-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_remove_mascota_edad_mascota_edad_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad_unidad',
            field=models.CharField(choices=[('años', 'Años'), ('meses', 'Meses')], default='años', max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad_valor',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
