# Generated by Django 6.0.6 on 2026-09-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_alter_mascota_edad_unidad_alter_mascota_edad_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcita',
            name='estado',
            field=models.CharField(choices=[('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='estado_pago',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Rechazado', 'Rechazado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20),
        ),
    ]
