# Generated by Django 6.0.6 on 2026-09-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_alter_solicitudcita_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20),
        ),
    ]
