# Generated by Django 6.0.6 on 2026-09-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_alter_solicitudcita_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcita',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='citas.mascota'),
        ),
    ]
