# Generated by Django 6.0.6 on 2026-09-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_alter_mascota_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcita',
            name='veterinario',
        ),
    ]
