# Generated by Django 6.0.6 on 2026-09-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_remove_solicitudcita_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcita',
            name='edad_unidad_mascota',
            field=models.CharField(blank=True, choices=[('años', 'Años'), ('meses', 'Meses')], default='años', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='edad_valor_mascota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='especie_mascota',
            field=models.CharField(blank=True, choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Conejo', 'Conejo')], max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='raza_mascota',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='sexo_mascota',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=20),
        ),
    ]
