# Generated by Django 6.0.6 on 2026-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0013_solicitudcita_edad_unidad_mascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('Canino', 'Canino'), ('Felino', 'Felino'), ('Conejo', 'Conejo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='especie_mascota',
            field=models.CharField(blank=True, choices=[('Canino', 'Canino'), ('Felino', 'Felino'), ('Conejo', 'Conejo')], max_length=20),
        ),
    ]
